### ISSUE TITLE
Is it possible to use in Angular 13?

### ISSUE THREAD

**Issue by gulsahkasdogan** [katoid/angular-grid-layout#28] opened 2021-12-27 14:14 UTC
First of all really nice work, congrats! I have tried to use in latest Angular version(13), I am getting "not a known element" error when I use kt-grid even though I imported it in app.module.ts 
I am providing the screenshot of the error, any help appreciated. Thanks in advance 

<img width="751" alt="Screen Shot 2021-12-27 at 17 12 25" src="https://user-images.githubusercontent.com/43780979/147479665-2b059985-cb3c-4896-90c4-b57149e58942.png">

**Comment by llorenspujol** [comment] 2022-01-20 09:22
Hi @gulsahkasdogan ! Thanks 😄 

It should work in angular 13, I make it normally work in this stackblitz: https://stackblitz.com/edit/angular-grid-layout-angular-13?file=src/app/playground/playground.module.ts (note that the styles are missing, but the grid just works)

Do you still have the issue? Are you sure you are importing the module in the right place? If the issue persists, would be helpful if you can reproduce it on a stackblitz or similar.

**Comment by sheikalthaf** [comment] 2022-02-06 14:06
@llorenspujol @gulsahkasdogan I'm working on the upgrade of angular 13.

**Comment by llorenspujol** [comment] 2022-02-07 10:19
Since version 1.1.0 of the lib Angular 13 is 'officially' supported, as it's peerDependencies indicate:

```typescript
  "peerDependencies": {
      "@angular/common": ">=12.0.0",
      "@angular/core": ">=12.0.0"
  },
```
Said that, with earlier version of the lib (versions less than 1.0.0), Angular 13, even not being officially supported was also working perfectly, as this [stackblitz](https://stackblitz.com/edit/angular-grid-layout-angular-13?file=src/app/playground/playground.module.ts) shows. 

Said that I am going to close the issue. 

@gulsahkasdogan If you still have problems, please reproduce them on stackblitz or similar to see exactly what is happening.

@sheikalthaf I would open an issue for Angular 13 upgrade. Last week we updated from Angular v11 to Angular v12. So the upgrade to Angular v13 would have to wait a little bit. We talk it on a separate issue.

**Closed by llorenspujol** 2022-02-07 10:19 UTC
