### ISSUE TITLE
Showing error for the version 1.2.0(latest)

### ISSUE THREAD

**Issue by experionathira** [katoid/angular-grid-layout#39] opened 2022-02-18 07:06 UTC
Hi,

I tried to npm install the latest version and it shows an error while running the application. Screenshot attached below
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/23093016/154634497-49d1a35a-cbf7-4ff5-84b6-9999f4a5f859.png)

**Comment by llorenspujol** [comment] 2022-02-18 09:20
In which Angular version are your testing it?

**Comment by experionathira** [comment] 2022-02-23 07:08
@llorenspujol  Version 10

**Comment by llorenspujol** [comment] 2022-02-23 09:39
Yep, version 1.2.0 only support angular version >= 12, as it's peerDependencies say. You can downgrade to @katoid/angular-grid-layout@0.2.0, that even it's peerDependencies are angular version 11, it works with angular 10 also.

Try it and if it works, close the issue please, thanks.

**Comment by llorenspujol** [comment] 2022-03-25 08:58
I am closing this issue. The cause and solution is well explained.

**Closed by llorenspujol** 2022-03-25 08:58 UTC
